# NumPy Random Sampling
Task 13 - Day 13

In [1]:
import numpy as np

rng = np.random.default_rng(42)

## Random integers and floating-point numbers

In [2]:
# random integers between 1 and 100
ints = rng.integers(1, 100, size=10)
print(ints)

[ 9 77 65 44 43 86  9 70 20 10]


In [3]:
# random floats between 0 and 1
floats = rng.random(5)
print(floats)

[0.97562235 0.7611397  0.78606431 0.12811363 0.45038594]


In [4]:
# random floats scaled to a custom range
scaled = rng.uniform(10, 20, size=5)
print(scaled)

[13.70798024 19.26764989 16.4386512  18.22761613 14.43414199]


In [5]:
# random numbers from a normal distribution
normal_vals = rng.normal(loc=50, scale=10, size=5)
print(normal_vals)

[41.40707537 53.68750784 40.41117399 58.78450301 49.50074089]


## Random samples from an array

In [6]:
students = np.array(["Asha", "Raj", "Meena", "Vikram", "Priya", "Karan"])

# sample without replacement - no repeats
sample = rng.choice(students, size=3, replace=False)
print(sample)

['Priya' 'Asha' 'Vikram']


In [7]:
# sample with replacement - repeats allowed
sample_wr = rng.choice(students, size=4, replace=True)
print(sample_wr)

['Karan' 'Meena' 'Karan' 'Priya']


In [8]:
# shuffling an array in place
deck = np.arange(1, 11)
rng.shuffle(deck)
print(deck)

[ 7  4  9  3 10  6  2  8  5  1]


## Reproducibility using a seed

In [9]:
# same seed -> identical results
rng1 = np.random.default_rng(7)
rng2 = np.random.default_rng(7)

a = rng1.integers(1, 100, size=5)
b = rng2.integers(1, 100, size=5)

print(a)
print(b)
print("Identical:", np.array_equal(a, b))

[94 62 68 89 58]
[94 62 68 89 58]
Identical: True


In [10]:
# no fixed seed -> different results each time
rng3 = np.random.default_rng()
rng4 = np.random.default_rng()

c = rng3.integers(1, 100, size=5)
d = rng4.integers(1, 100, size=5)

print(c)
print(d)
print("Identical:", np.array_equal(c, d))

[35 51 81  3 11]
[22 53  2 29 70]
Identical: False


## Generating a small simulated dataset

In [11]:
# 6 students, 3 subjects, marks between 40 and 100
sim_marks = rng.integers(40, 100, size=(6, 3))
print(sim_marks)

[[61 98 64]
 [59 94 62]
 [44 68 87]
 [51 67 47]
 [81 68 59]
 [53 73 80]]


In [12]:
print("Average per subject:", np.mean(sim_marks, axis=0))

Average per subject: [58.16666667 78.         66.5       ]


## Interview questions

**Why are random numbers useful in data science?**
They're used to simulate data when real data isn't available yet, to split datasets into train/test sets, to shuffle data so patterns aren't learned from ordering, and to initialize models before training. Random sampling also underlies techniques like bootstrapping and Monte Carlo simulation for estimating uncertainty.

**What is a random seed?**
A starting value that initializes the random number generator's internal state. The sequence of "random" numbers a computer produces is actually deterministic given that starting point, so setting the same seed makes the generator produce the exact same sequence every time it runs.

**Why is reproducibility important?**
Without a fixed seed, results change every run, which makes debugging, testing, and comparing experiments unreliable — a change in output could be from a code fix or just from a different random draw. Setting a seed means results can be checked, shared, and reproduced exactly by someone else running the same code.